apiVersion: v1
kind: Pod
metadata:
  name: gpushare-test-pod
spec:
  restartPolicy: OnFailure
  schedulerName: aliyun
  containers:
    - name: gpushare-test-pod
      image: "cheyang/gpu-player:v2"
      resources:
        limits:
         aliyun.com/gpu-mem: 5

